# Choose a build environment
dist: xenial

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - /home/travis/.rvm/

services:
  - "postgresql"

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- cd api/
- stack --no-nix --no-terminal --install-ghc test --only-dependencies

before_script:
  - psql -U postgres -c "CREATE DATABASE test;"
  - cd ../migration
  - bundle
  - RAILS_ENV=test rake db:drop db:create db:migrate

script:
# Build the package, its tests, and its docs and run the tests
- cd ../api
- stack --no-nix --no-terminal test
