version: '3'
services:
  postgres-test:
    image: postgres:11.2
    env_file: .env
    environment:
      - POSTGRES_DB=test
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5433:5432"