name: patchGirl

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NamedFieldPuns
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - RecordWildCards

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - patchGirl
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  patchGirl:
    main: exe/Main.hs
    dependencies:
      - patchGirl

dependencies:
  - base
  - servant
  - servant-client
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-auth-client
  - servant-flatten
  - transformers
  - aeson
  - wai
  - warp
  - warp-tls
  - postgresql-simple
  - text
  - servant-elm
  - elm-bridge
  - aeson-qq
  - unordered-containers
  - lens
  - mtl
  - case-insensitive
  - cookie
  - bytestring
  - utf8-string
  - hailgun
  - email-validate
  - dhall
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - time
  - jose
  - wai-middleware-prometheus
  - prometheus-client
  - prometheus-metrics-ghc
  - uuid
  - strings
  - control-monad-free