resolver: lts-14.4
packages:
  - '.'

extra-deps:
  - servant-flatten-0.2
  - servant-elm-0.7.1
  - hailgun-0.4.2
  - http-client-0.5.14
  - dhall-1.28.0
  - atomic-write-0.2.0.7
  - prettyprinter-1.5.1


nix:
  enable: true
  packages: [postgresql, zlib]