name: patchgirl-desktop

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NamedFieldPuns
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - RecordWildCards
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeApplications # allows you to use visible type application in expressions, eg: show (read @Int "5")

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -Wincomplete-patterns
  - -Wcompat # make code future compatible to adapt to new features
  - -Wincomplete-record-updates # catch what are essentially partial pattern-matches
  #- -Wincomplete-uni-patterns
  - -Wredundant-constraints # help remove unnecessary typeclass constraints on functions


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - patchgirl-desktop
      - servant-client

library:
  source-dirs:
    - src

executables:
  patchgirl-desktop-exe:
    main: app/Main.hs
    dependencies:
      - patchgirl-desktop
      - patchgirl-web

dependencies:
  - base
  - webviewhs
