name: patchgirl-runner

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NamedFieldPuns
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - RecordWildCards
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - TypeApplications # allows you to use visible type application in expressions, eg: show (read @Int "5")

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -Wincomplete-patterns
  - -Wcompat # make code future compatible to adapt to new features
  - -Wincomplete-record-updates # catch what are essentially partial pattern-matches
  #- -Wincomplete-uni-patterns
  - -Wredundant-constraints # help remove unnecessary typeclass constraints on functions


tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - servant-client

executables:
  patchgirl-runner-exe:
    source-dirs:
      - src
      - app
    main: Main.hs
#    ghc-options:
#    - -static # link haskell library statically
#    - -optl-static
#    - -optl-pthread
#    extra-lib-dirs: /lib/x86_64-linux-gnu
#    extra-lib-dirs: /usr/lib/x86_64-linux-gnu
#    cc-options: -static
#    ld-options: -static

dependencies:
  - patchgirl-web
  - base
  - wai-cors
  - servant-server
  - utf8-string
  - dhall
  - aeson
  - wai
  - warp
  - mtl
  - bytestring
  - uuid
  - lens
  - case-insensitive
  - http-client
  - http-client-tls
  - http-conduit
  - http-types
  - say
  - containers
  - connection
  - wai-cors
  - wai-middleware-prometheus
  - prometheus-client
  - prometheus-metrics-ghc
  - stm
