name: example-servant-minimal

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - example-servant-minimal
      - servant-client
      - warp >= 3.2.4
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  example-servant-minimal:
    main: exe/Main.hs
    dependencies:
      - example-servant-minimal

dependencies:
  - base
  - servant
  - servant-server
  - servant-auth
  - servant-auth-server
  - servant-auth-client
  - servant-flatten
  - transformers
  - aeson
  - wai
  - warp
  - warp-tls
  - postgresql-simple
  - text
  - servant-elm
  - elm-bridge
  - aeson-qq
  - unordered-containers
  - lens
  - mtl
  - case-insensitive
  - cookie
  - bytestring
  - utf8-string
  - hailgun
  - email-validate
  - mtl
  - dhall
  - http-client
  - http-conduit
  - http-types
